name: Unit and Functional Tests

on:
  push:
      branches: [main]
  pull_request:
    branches: [main]

jobs:
    functional_tests:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash -l {0}  
      steps:
        - uses: actions/checkout@v2
        - uses: conda-incubator/setup-miniconda@v2
          with:
            activate-environment: base
            environment-file: environment.yml
        - run: |
            python -m pip install --upgrade pip
            python -m pip install matplotlib
            python -m pip install numpy
            bash tests/test_hw7.sh
    code_style:
      runs-on: ubuntu-latest
      steps: 
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with: 
          activate-environment: base
          environment-file: environment.yml 
      - run: |
          python -m pip install --upgrade pip
          python -m pip install pycodestyle
          pycodestyle $(git ls-files "*.py")
      
    unit_tests:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - run: | 
          python -m unittest tests/test_hw7.py
